import { BrowserModule } from "@angular/platform-browser";
import { NgModule } from "@angular/core";

import { AppRoutingModule } from "./app-routing.module";
import { AppComponent } from "./app.component";
import { BrowserAnimationsModule } from "@angular/platform-browser/animations";
import { ErrorComponent } from "./error/error.component";
import { AutoGeneratedComponent } from "./auto-generated/auto-generated.component";
//import { EldeebModule, EldeebService } from "eldeeb";

@NgModule({
  declarations: [AppComponent, ErrorComponent, AutoGeneratedComponent],
  imports: [
    BrowserModule.withServerTransition({ appId: "serverApp" }),
    AppRoutingModule,
    BrowserAnimationsModule
    //  EldeebModule
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule {
  /*
  constructor(public eldeebService: EldeebService) {
    console.log("*** AppModule started ***");
    eldeebService.test();
  }*/
}
