import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import config from 'config';
import { AppRoutingModule } from './app-routing.module';
import { AppComponent } from './app.component';
import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
import { ErrorComponent } from './error/error.component';
import { AutoGeneratedComponent } from './auto-generated/auto-generated.component';
import { AngularFireModule } from '@angular/fire';
import { AngularFireAuthModule } from '@angular/fire/auth';
import { DxButtonModule } from 'devextreme-angular';
import { MetaService } from './meta.service';
// import { EldeebModule, EldeebService } from "eldeeb";

@NgModule({
  declarations: [AppComponent, ErrorComponent, AutoGeneratedComponent],
  imports: [
    BrowserModule.withServerTransition({ appId: 'serverApp' }),
    AppRoutingModule,
    BrowserAnimationsModule,
    AngularFireModule.initializeApp(config.firebase, 'my-app-name'), // firebase core (required):  firebase/app
    AngularFireAuthModule, // add firebase products such as Auth, database, firestore, ...
    DxButtonModule
  ],
  providers: [MetaService],
  bootstrap: [AppComponent]
})
export class AppModule {
  /*
  constructor(public eldeebService: EldeebService) {
    console.log("*** AppModule started ***");
    eldeebService.test();
  }*/
}
